// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFYY1lMZDFFXI4OM8XQsb2mtEFiVa5Wl8',
    appId: '1:751415252008:web:45f968276f26cb5691d11d',
    messagingSenderId: '751415252008',
    projectId: 'vmart-2c133',
    authDomain: 'vmart-2c133.firebaseapp.com',
    storageBucket: 'vmart-2c133.appspot.com',
    measurementId: 'G-V8K0DKBM9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNENndH-DK92iGWa0tDuUIcXu6Mrc7F0E',
    appId: '1:751415252008:android:a9c661688ba4ce3d91d11d',
    messagingSenderId: '751415252008',
    projectId: 'vmart-2c133',
    storageBucket: 'vmart-2c133.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE2gnTQY6H1Tbeo23SJvs-ZrBdEYnMFFU',
    appId: '1:751415252008:ios:54f091930c2a773a91d11d',
    messagingSenderId: '751415252008',
    projectId: 'vmart-2c133',
    storageBucket: 'vmart-2c133.appspot.com',
    androidClientId: '751415252008-7v7fihv4o2voje6obobl33qds7bm3e5o.apps.googleusercontent.com',
    iosClientId: '751415252008-lug0hld6b5ki358g6l6o4912fgpisah1.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );
}
